### ISSUE TITLE
Cant find this on play store

### ISSUE THREAD

**Issue by abantoo** [fuadmiazi/Nunu-Dodger-18-#1]
Hi, I have this weird issue.

**Comment by fuadmiazi** [comment]
Pay me $25 dollar to solve this issue.

**Comment by fuadmiazi** [comment]
Or you can simply download from here: https://fuadmiazi.itch.io/nunu-dodger

**Comment by fuadmiazi** [comment]
Or you can download the apk from here in the repository. 
https://github.com/fuadmiazi/Nunu-Dodger-18-/blob/main/Android%20Build/Nunu%20Dodger%201.apk
